// Auto-generated by generateMarkerImages.js
export const markerImages = {
  "California State University, Fullerton": {
    "csuf promenade archway": [
      require("./assets/California State University, Fullerton/csuf promenade archway/image1.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image2.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image3.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image4.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image5.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image6.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image7.jpg"),
      require("./assets/California State University, Fullerton/csuf promenade archway/image8.jpg"),
    ],
    "langsdorf fountain": [
      require("./assets/California State University, Fullerton/langsdorf fountain/image1.jpg"),
      require("./assets/California State University, Fullerton/langsdorf fountain/image2.jpg"),
      require("./assets/California State University, Fullerton/langsdorf fountain/image3.jpg"),
      require("./assets/California State University, Fullerton/langsdorf fountain/image4.jpg"),
    ],
    "palm tree path": [
      require("./assets/California State University, Fullerton/palm tree path/image1.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image2.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image3.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image4.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image5.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image6.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image7.jpg"),
      require("./assets/California State University, Fullerton/palm tree path/image8.jpg"),
    ],
    "titans letters": [
      require("./assets/California State University, Fullerton/titans letters/iamge4.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image1.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image2.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image3.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image5.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image6.jpg"),
      require("./assets/California State University, Fullerton/titans letters/image7.jpg"),
    ],
  },
  "San Diego State Universtiy": {
    "aztec student union": [
      require("./assets/San Diego State Universtiy/aztec student union/image1.jpg"),
    ],
    "hardy tower": [
      require("./assets/San Diego State Universtiy/hardy tower/image1.jpg"),
    ],
    "hepner hall": [
      require("./assets/San Diego State Universtiy/hepner hall/image1.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image2.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image3.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image4.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image5.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image6.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image7.jpg"),
      require("./assets/San Diego State Universtiy/hepner hall/image8.jpg"),
    ],
    "sdsu imperial valley’s front lawn": [
      require("./assets/San Diego State Universtiy/sdsu imperial valley’s front lawn/image1.jpg"),
    ],
  },
  "San Jose State University": {
    "Paseo de César Chávez": [
      require("./assets/San Jose State University/Paseo de César Chávez/image1.jpg"),
      require("./assets/San Jose State University/Paseo de César Chávez/image2.jpg"),
      require("./assets/San Jose State University/Paseo de César Chávez/image3.jpg"),
      require("./assets/San Jose State University/Paseo de César Chávez/image4.jpg"),
      require("./assets/San Jose State University/Paseo de César Chávez/image5.jpg"),
      require("./assets/San Jose State University/Paseo de César Chávez/image6.jpg"),
    ],
    "spartan memorial": [
      require("./assets/San Jose State University/spartan memorial/image1.jpg"),
      require("./assets/San Jose State University/spartan memorial/image2.jpg"),
    ],
    "tower hall": [
      require("./assets/San Jose State University/tower hall/image1.jpg"),
      require("./assets/San Jose State University/tower hall/image2.jpg"),
      require("./assets/San Jose State University/tower hall/image3.png"),
      require("./assets/San Jose State University/tower hall/image4.jpg"),
    ],
  },
  "Standford University": {
    "memorial church": [
      require("./assets/Standford University/memorial church/image1.jpg"),
      require("./assets/Standford University/memorial church/image2.jpg"),
    ],
    "science & engineering quad courtyard": [
      require("./assets/Standford University/science & engineering quad courtyard/6de108535c683a218d9e2e80a76b1433.jpg"),
      require("./assets/Standford University/science & engineering quad courtyard/95e7ea08cffc5468a6f9cf134d638773.jpg"),
      require("./assets/Standford University/science & engineering quad courtyard/bbec91f061cd58d8d2f4c3350de16f5b.jpg"),
    ],
  },
  "University of California Santa Cruz": {
    "mchenry library": [
      require("./assets/University of California Santa Cruz/mchenry library/image1.jpg"),
      require("./assets/University of California Santa Cruz/mchenry library/image2.jpg"),
    ],
    "pedestrian footbridges": [
      require("./assets/University of California Santa Cruz/pedestrian footbridges/image1.jpg"),
      require("./assets/University of California Santa Cruz/pedestrian footbridges/image2.jpg"),
      require("./assets/University of California Santa Cruz/pedestrian footbridges/image3.jpg"),
      require("./assets/University of California Santa Cruz/pedestrian footbridges/image4.jpg"),
    ],
    "university of california santa cruz sign": [
      require("./assets/University of California Santa Cruz/university of california santa cruz sign/image1.jpg"),
      require("./assets/University of California Santa Cruz/university of california santa cruz sign/image2.jpg"),
    ],
  },
  "University of California, Irvine": {
    "aldrich park": [
      require("./assets/University of California, Irvine/aldrich park/image1.jpg"),
      require("./assets/University of California, Irvine/aldrich park/image2.jpg"),
      require("./assets/University of California, Irvine/aldrich park/image3.jpg"),
    ],
    "aldrich park benches": [
      require("./assets/University of California, Irvine/aldrich park benches/image1.jpg"),
    ],
    "aldrich park red flowers ": [
      require("./assets/University of California, Irvine/aldrich park red flowers /image1.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image2.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image3.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image4.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image5.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image6.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image7.jpg"),
      require("./assets/University of California, Irvine/aldrich park red flowers /image8.jpg"),
    ],
    "langson library": [
      require("./assets/University of California, Irvine/langson library/image1.jpg"),
      require("./assets/University of California, Irvine/langson library/image2.jpg"),
      require("./assets/University of California, Irvine/langson library/image3.jpg"),
      require("./assets/University of California, Irvine/langson library/image4.jpg"),
    ],
    "science library": [
      require("./assets/University of California, Irvine/science library/image1.jpg"),
      require("./assets/University of California, Irvine/science library/image2.jpg"),
      require("./assets/University of California, Irvine/science library/image3.jpg"),
    ],
  },
  "Univertiy of California, Santa Barbara": {
    "flowers around henley gate": [
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image1.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image2.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image3.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image4.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image5.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/flowers around henley gate/image6.jpg"),
    ],
    "harley gate": [
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image1.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image2.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image3.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image4.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image5.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image6.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/harley gate/image7.jpg"),
    ],
    library: [
      require("./assets/Univertiy of California, Santa Barbara/library/image1.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/library/image2.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/library/image3.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/library/image4.jpg"),
      require("./assets/Univertiy of California, Santa Barbara/library/image5.jpg"),
    ],
  },
};
